# Generated by Django 4.0.2 on 2022-03-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('technologies', models.TextField(blank=True, null=True)),
                ('functions', models.TextField(blank=True, null=True)),
                ('link', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
